### ISSUE TITLE
OV5640  in Nano Pi Duo 2

### ISSUE THREAD

**Issue by scizors** [avafinger/ov5640#7]
Hi, 
I am using Nani Pi Duo 2. I would like to know this solution will work on this board. 

I am using,
:uname -a
:Linux nanopiduo2 5.10.16-sunxi #21.02.2 SMP Sun Feb 14 21:12:17 CET 2021 armv7l armv7l armv7l GNU/Linux

Thanks in advance

**Comment by avafinger** [comment]
This driver is for kernel 3.10 only.
